### ISSUE TITLE
Conditional Tagging

### ISSUE THREAD

**Issue by madhuioe** [adejoux/nmon2influxdb#42]
Hello Alain,
I have issue on tagging. Below is the part of my configuration file:
In our case, there are number of servers on different locations belongs to "REGION" (NA, EMEA, APAC). Hostnames are held on "Match" section (aixhost1|aixhost2|aixhost3|aixhost4.......and so on). 
Is there any possibility that any host (aixhost1|aixhost2|aixhost3|aixhost4....) could pick any values (NA|AMEA|APAC) based on their location?
[[input]]
  Measurement="CPU_ALL"
  Name="host"
  Match="^aixhost1|aixhost2|aixhost3|aixhost4$"
  [[input.tag]]
    Name="BUSINESSCLASS"
    Value="GOLD"
  [[input.tag]]
    Name="HOSTTYPE"
    Value="PHYSICAL"
  [[input.tag]]
    Name="OSTYPE"
    Value="AIX"
  [[input.tag]]
    Name="REGION"
    Value="NA"

Thanks,
Madhu

**Comment by adejoux** [comment]
Hello,

I am not sure if I understand correctly. 

With your current configuration, aixhost1 to aixhost4 will have region set to NA. 

If you would like to have them in different regions, you could do something like that:

```` toml
[[input]]
Measurement="CPU_ALL"
Name="host"
Match="^aixhost1|aixhost2|aixhost3|aixhost4$"
[[input.tag]]
Name="BUSINESSCLASS"
Value="GOLD"
[[input.tag]]
Name="HOSTTYPE"
Value="PHYSICAL"
[[input.tag]]
Name="OSTYPE"
Value="AIX"
[[input]]
Measurement="CPU_ALL"
Name="host"
Match="^aixhost1|aixhost2$"
[[input.tag]]
Name="REGION"
Value="EMEA"
[[input]]
Measurement="CPU_ALL"
Name="host"
Match="^aixhost4$"
[[input.tag]]
Name="REGION"
Value="APAC"
````

Is it what you means?

Thanks,

Alain
